product/apps/website/urls.py
from django.urls import path, include
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('order/<int:order_id>/detail/', views.OrderDetailView.as_view(), name='order-detail'),
]

product/urls.py
from django.urls import path, include
from django.contrib import admin
from product.apps.apidoc.config import schema_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/doc/(?P<format>\.json|\.yaml)/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('', include("product.apps.website.urls")),
    path('store/', include("product.apps.store.urls")),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:  # Adding statics only if debug = True
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/apps/website/models.py
from django.db import models

# Create your models here.

product/apps/website/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class IndexView(LoginRequiredMixin, View):
    template_name = "index.html"

    def get(self, request):
        ctx = {}
        return render(request, self.template_name, ctx)


class OrderDetailView(LoginRequiredMixin, View):
    template_name = "order_detail.html"

    def get(self, request, order_id):
        ctx = {'order_id': order_id}
        return render(request, self.template_name, ctx)

product/apps/website/templates/index.html
{% extends 'base_admin.html' %}
{% load i18n static %}
 {% block extra-css %}
 {% endblock extra-css %}
{% block container %}
    <div class="row" style="padding: 40px" id="store" v-cloak>
            <h4>{% trans 'Listado de pedidos' %}</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% trans 'Ciente' %}</th>
                <th scope="col">{% trans 'Tipo' %}</th>
                <th scope="col">{% trans 'Fecha del pedido' %}</th>
                <th scope="col">{% trans 'Fecha de surtido' %}</th>
                <th scope="col">{% trans '¿Urge?' %}</th>
                <th scope="col">{% trans 'Total' %}</th>
                <th scope="col">{% trans 'Ver detalle' %}</th>
            </tr>
            </thead>
            <tbody>
            <tr v-for="item in orders">
                <th scope="row">[[item.id]]</th>
                <td>[[item.customer.first_name]] [[item.customer.last_name]]</td>
                <td>
                   <label v-if="item.type==='CD'">{% trans 'Centro de distribución' %}</label>
                   <label v-if="item.type==='SU'">{% trans 'Sucursal' %}</label>
                   <label v-if="item.type==='EA'">{% trans 'Empresa asociada' %}</label>
                </td>
                <td>[[item.timestamp]]</td>
                <td>[[item.assortment_date]]</td>
                <td>
                    <span class="badge badge-pill badge-warning" v-if="item.is_urgent">{% trans 'SI' %}</span>
                    <span class="badge badge-pill badge-success" v-else>{% trans 'NO' %}</span>
                </td>
                <td>$[[item.total]]</td>
                <td><a :href="'/order/'+item.id + '/detail/'">Ver</a></td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock container %}
{% block extra-js %}
    <script>
        _orderIdSelected = null;
    </script>
    <script src="{% static 'dist/js/store.js' %}?vid={{ vid }}"></script>
{% endblock extra-js %}

product/apps/website/templates/order_detail.html
{% extends 'base_admin.html' %}
{% load i18n static %}
{% block extra-css %}
{% endblock extra-css %}
{% block container %}
    <div id="store" v-cloak style="padding: 40px">
        <div class="row" style="margin-bottom: 30px">
            <h4>{% trans 'Información general' %}</h4>
        </div>
        <div class="row">
            <div class="col-md-4">
                <img :src="[[orderData.customer.photo]]" alt="" width="200px">
            </div>
            <div class="col-md-4">
                <div class="row">
                    <label><strong>{% trans 'Cliente' %}:</strong> [[orderData.customer.first_name]] [[orderData.customer.last_name]]</label>
                </div>
                <div class="row">
                    <label><strong>{% trans 'Dirección' %}:</strong> [[orderData.customer.address]]</label>
                </div>
                <div class="row">
                    <strong>{% trans 'Tipo de pedido' %}: </strong>
                    <label v-if="orderData.type==='CD'">{% trans 'Centro de distribución' %}</label>
                    <label v-if="orderData.type==='SU'">{% trans 'Sucursal' %}</label>
                    <label v-if="orderData.type==='EA'">{% trans 'Empresa asociada' %}</label>
                </div>
                <div class="row" v-if="orderData.type==='CD'">
                    <label><strong>{% trans 'Almacén' %}: </strong>[[orderData.custom_data.stock]]</label>
                </div>
                <div class="row" v-if="orderData.type==='SU'">
                    <label><strong>{% trans 'Referencia' %}: </strong>[[orderData.custom_data.reference]]</label>
                    <label><strong>{% trans 'Código de sucursal' %}: </strong>[[orderData.custom_data.num_branch_office]]</label>
                </div>
                <div class="row" v-if="orderData.type==='EA'">
                    <label><strong>{% trans 'Referencia' %}: </strong>[[orderData.custom_data.reference]]</label>
                    <label><strong>{% trans 'Código de socio' %}: </strong>[[orderData.custom_data.code_partner]]</label>
                </div>
                <div class="row">
                    <label><strong>{% trans 'Fecha del pedido' %}: </strong>[[orderData.timestamp]]</label>
                </div>
                <div class="row">
                    <label><strong>{% trans 'Fecha de surtido' %}: </strong>[[orderData.assortment_date]]</label>
                </div>
                <div class="row">
                    <label><strong>{% trans 'Total' %}: </strong>$[[orderData.total]]</label>
                </div>
                <div class="row">
                    <label> <strong>{% trans '¿Urgente?' %}:</strong>
                        <span class="badge badge-pill badge-warning" v-if="orderData.is_urgent">{% trans 'SI' %}</span>
                        <span class="badge badge-pill badge-success" v-else>{% trans 'NO' %}</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="row">
            <h4>{% trans 'Detalle del pedido' %}</h4>
        </div>
        <div class="row">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">{% trans 'Producto' %}</th>
                    <th scope="col">{% trans 'Descripción' %}</th>
                    <th scope="col">{% trans 'Proveedor' %}</th>
                    <th scope="col">{% trans 'Precio' %}</th>
                    <th scope="col">{% trans 'Cantidad' %}</th>
                    <th scope="col">{% trans 'Total' %}</th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="item in orderData.detail">
                    <td>[[item.product_provider.product.name]]</td>
                    <td>[[item.product_provider.product.description]]</td>
                    <td>[[item.product_provider.provider.name]]</td>
                    <td>[[item.sale_price]]</td>
                    <td>[[item.quantity]]</td>
                    <td>[[item.total]]</td>
                </tr>
                </tbody>
            </table>
        </div>
    <div class="row">
        <a href="{% url 'website:index' %}" class="btn btn-secondary">{% trans 'Regresar' %}</a>
    </div>
    </div>

{% endblock container %}
{% block extra-js %}
    <script>
        _orderIdSelected = {{ order_id }};
    </script>
    <script src="{% static 'dist/js/store.js' %}?vid={{ vid }}"></script>
{% endblock extra-js %}